🎨 sort release in reverse order for bin/activate
openfun/openedx-docker pull request #240
Opened 2020-09-01 14:29 UTC by slandrault

## Purpose

In order to easily identify the history of the different release
when running the bin/activate command, a sort operation is added
to have the most recent branches first.

## Proposal

Adding a `sort` command enables to sort the list of release (in reverse order) to have the most recent release first (sorted by alphabetical order)

Before (unordered):
```plain
Select an available flavored release to activate:
[1] master/bare (default)
[2] dogwood/3/fun
[3] dogwood/3/bare
[4] ironwood/2/bare
[5] eucalyptus/3/wb
[6] eucalyptus/3/bare
[7] hawthorn/1/oee
[8] hawthorn/1/bare
```

After (most recent first):
```plain
Select an available flavored release to activate:
[1] master/bare (default)
[2] ironwood/2/bare
[3] hawthorn/1/oee
[4] hawthorn/1/bare
[5] eucalyptus/3/wb
[6] eucalyptus/3/bare
[7] dogwood/3/fun
[8] dogwood/3/bare
```

2020-09-01 14:35 UTC, sampaccoud approved these changes
Nice!

<img src="https://media.giphy.com/media/W0Vz7zDK7vgMBc2fpw/source.gif">

2020-09-01 14:39 UTC, madmatah requested changes
Nice, thanks!

Just a comment about the commit message subject. As described in our [gitbook](https://openfun.gitbooks.io/handbook/content/git.html), you should add a scope, i.e. : 
`🎨 (project) sort release in reverse order for bin/activate`

2020-09-01 14:41 UTC, slandrault commented
> As described in our [gitbook](https://openfun.gitbooks.io/handbook/content/git.html), you should add a scope, i.e. :
> `🎨 (project) sort release in reverse order for bin/activate`
True. What kind of project would be most accurate here? "(activate)"?

2020-09-01 14:43 UTC, madmatah commented
> > As described in our [gitbook](https://openfun.gitbooks.io/handbook/content/git.html), you should add a scope, i.e. :
> > `🎨 (project) sort release in reverse order for bin/activate`
> 
> True. What kind of project would be most accurate here? "(activate)"?

I looked into the commit history and the scope `(bin)` is sometime used for the scripts in the `bin/` directory.
Also, the `(project)` scope is often used for all that concerns the project structure / build tools.

2020-09-01 14:49 UTC, madmatah approved these changes
![](https://media.giphy.com/media/FpKKILCKqNIgIE1GZf/giphy.gif)

2020-09-01 15:44 UTC, jmaupetit reviewed
Why not sorting releases alphabetically?

2020-09-02 06:32 UTC, slandrault commented
> Why not sorting releases alphabetically instead?

To get the most recent first (as we are usually reading from top to bottom) and therefore:
- Easily get the history of releases
- having only one digit to press instead of two when number of versions increases (and thus less prone to typing error)

2020-09-02 06:56 UTC, jmaupetit reviewed
I just realize that you are talking of OpenEdx releases, not `openedx-docker`... and was looking for black magic I don't understand in your command :sweat_smile:

2020-09-02 06:56 UTC, jmaupetit commented on bin/activate
> +        sort -f -i -r |
Are `-f` and `-i` flags required in this case?
```suggestion
        sort -r |
```

2020-09-02 06:58 UTC, slandrault commented on bin/activate
> +        sort -f -i -r |
There are not *required* but more for "futureproofing" the script :D . No problem to remove then to make the script maybe more understandable.

2020-09-02 07:10 UTC, jmaupetit commented on bin/activate
> +        sort -f -i -r |
Do as you please :hugs: I you leave all flags, can you merge them (`sort -fir`)?

2020-09-02 07:11 UTC, jmaupetit approved these changes

2020-09-03 08:07 UTC, merged