🚧(project) prevent make bootstrap to be run from root user
openfun/openedx-docker pull request #247
Opened 2020-09-08 12:44 UTC by slandrault

**This is a draft, to discuss implementation**

## Purpose

In order to not mess up user filesystem, the build should not be
run as a root user.
This commit add a "ensure-not-root" make target that will check
if the user running the make is not with an id = 0 (root).

## Proposal

To guard any make target from being run as root, a `ensure-not-root` target can be called first. If the user is root, then the command will fail with a warning message.

2020-09-08 12:44 UTC, slandrault commented
For the moment, the solution is implemented as an "fail if run as root". I'll evaluate the feasibility of achieving similar feature with a warning+confirmation instead of failing all the time.

2020-09-08 14:02 UTC, slandrault commented
The target has been updated. In case of root call, the command will now ask for confirmation before continuation instead of leaving.

2020-09-08 15:18 UTC, jmaupetit commented on releases/dogwood/3/fun/Dockerfile
> +      echo "User with ID ${DOCKER_UID} already exists." && \
We are not sure of the reason why the useradd command fails:

```suggestion
      echo "Skip user creation (user with ID ${DOCKER_UID} already exists?)" && \
```

2020-09-08 15:27 UTC, slandrault commented on releases/dogwood/3/fun/Dockerfile
> +      echo "User with ID ${DOCKER_UID} already exists." && \
Good point

2020-09-09 07:29 UTC, jmaupetit reviewed
Maybe other commands that create/access mounted volumes should also have the `ensure-non-root` dependency (_e.g._ `build`, `build-dev`, `tree`), WDYT?

2020-09-09 07:51 UTC, slandrault commented
> Maybe other commands that create/access mounted volumes should also have the `ensure-non-root` dependency (_e.g._ `build`, `build-dev`, `tree`), WDYT?

They could, but that means that when bootstrap will be run it will ask for confirmation when reaching each of those target... Maybe not very user friendly?

2020-09-09 08:03 UTC, jmaupetit commented
> Maybe not very user friendly?

At least the user will understand that this is not the recommended way to do things :joy:

2020-09-17 09:47 UTC, slandrault commented
A side effect would be that the bootstrap won't be able to run by itself until completion because the user would have to validate several times that he is ok to continue as sudo...

2020-09-17 10:21 UTC, sampaccoud commented
We could request to set an env variable to be allowed to run any command as sudo?

2020-09-17 11:31 UTC, slandrault commented
> We could request to set an env variable to be allowed to run any command as sudo?

:+1:  Sounds like a an elegant solution. If the variable is set then go, if not then warning message and fail nicely.

2020-09-17 13:29 UTC, lunika reviewed
The makefile is self documented with the `help` task. All comments starting by `##` after a task name must be kept and you will see them when you run `make` or `make help`

2020-09-17 13:29 UTC, lunika commented on Makefile
> +verify-root:  # Make sure the user calling this is not currently root
In your commit message you called it `ensure-not-root`

2020-09-17 13:29 UTC, lunika commented on Makefile
> +verify-root:  # Make sure the user calling this is not currently root
```suggestion
verify-root:  ## Make sure the user calling this is not currently root
```

2020-09-17 13:29 UTC, lunika commented on Makefile
> +# Import demo course from edX repository
```suggestion
```

2020-09-17 13:29 UTC, lunika commented on Makefile
> +demo-course:
```suggestion
demo-course: ## import demo course from edX repository
```

2020-09-17 13:29 UTC, lunika commented on Makefile
> +# Start assets watcher (front-end development)
```suggestion

```

2020-09-17 13:29 UTC, lunika commented on Makefile
> +	tree \
```suggestion
	tree
dev-watch: ## Start assets watcher (front-end development)
```

2020-09-17 13:29 UTC, lunika commented on releases/dogwood/3/bare/Dockerfile
> +    useradd --create-home --home-dir /home/edx --uid ${DOCKER_UID} --gid ${DOCKER_GID} edx || \
You should keep the multiline command, we use this format to improve readability

2020-09-17 13:29 UTC, lunika commented on .circleci/config.yml
>    # Note that the job name should match the EDX_RELEASE value
in your commit title: 

`s/prevent make bootstrap to be run from root user/prevent make bootstrap to be run as root user/`

2020-09-17 13:32 UTC, jmaupetit commented on Makefile
> +verify-root:  # Make sure the user calling this is not currently root
What about `check-root-user`?

2020-09-17 14:09 UTC, slandrault commented on Makefile
> +# Import demo course from edX repository
If we do that then we break the "codestyle" of the file. Everytime a target is on multiple line then the comment is above the command, only when there is no / the comment is next to the target name.

2020-09-17 14:39 UTC, lunika commented on Makefile
> +# Import demo course from edX repository
Take a look at the `help` task, this task is using comments starting with `##`

2020-09-17 14:39 UTC, lunika commented on Makefile
> +# Import demo course from edX repository
Also look this article https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html

2020-09-17 14:49 UTC, slandrault commented on Makefile
> +# Import demo course from edX repository
Ohhhh ok yes I understand why now! Thx!

2020-10-06 13:39 UTC, jmaupetit requested changes
Rules that may create files and thus should have the `check-root-user` dependency are:

- `build`
- `clean`
- `create-symlinks`
- `demo-course`
- `dev-assets`
- `dev-build`
- `dev-install`
- `dev-watch`
- `fetch-demo`
- `fetch-release`
- `migrate`
- `run`
- `tree`

2020-10-06 13:39 UTC, jmaupetit commented on Makefile
> +	@if [ $(shell id -u) -eq 0 ]; \
It is generally safer to use the double bracket syntax:

```suggestion
	@if [[ $(shell id -u) -eq 0 ]]; \
```

Reference: http://mywiki.wooledge.org/BashGuide/Practices#Bash_Tests

2020-10-06 15:04 UTC, slandrault commented on Makefile
> +  check-root-user \
Fair point.

2020-10-07 13:55 UTC, jmaupetit commented on releases/dogwood/3/bare/Dockerfile
>      rm -rf /var/lib/apt/lists/*
Your commit message scope should be: `flavors/*` and I would rephrase your commit title as:

:hammer:(flavors/*) allow builds using the root user

If you hesitate on a scope, check the project's commits history!

2020-10-13 13:04 UTC, jmaupetit approved these changes
![](https://media0.giphy.com/media/xT9IgzUuC5Ss6ZnTEs/giphy-downsized-medium.gif)

2020-10-13 13:19 UTC, merged